version: '2'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    # we use image for faster developing with `npm install` already run
    image: ${DEV_DOCKER_IMAGE}
    command: bash -c "npm run start"
    environment:
      NODE_ENV: development
    volumes:
      - .:/opt/app
    ports:
      - 4200:4200